# Generated by Django 4.0.6 on 2023-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_token',
            new_name='email_verification_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='forget_password',
            new_name='forget_password_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_logout_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
