# Generated by Django 4.0.6 on 2023-02-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
    ]
